### ISSUE TITLE
Неожиданный результат при анализе некорректной программы

### ISSUE THREAD

**Issue by kajigor** [e2e4b6b7/Simple-prolog-parser#3]
Вход: [e06.txt](https://github.com/e2e4b6b7/Simple-prolog-parser/files/5348850/e06.txt)
Выход: `1`

Вход: [e07.txt](https://github.com/e2e4b6b7/Simple-prolog-parser/files/5348851/e07.txt)
Выход: `1`

Вход: [e08.txt](https://github.com/e2e4b6b7/Simple-prolog-parser/files/5348852/e08.txt)
Выход: `:`

**Comment by e2e4b6b7** [comment]
Он стеснялся, вроде исправил.
