### ISSUE TITLE
HW05: Результат при синтаксической ошибке

### ISSUE THREAD

**Issue by kajigor** [e2e4b6b7/Simple-prolog-parser#4]
[e02.txt](https://github.com/e2e4b6b7/Simple-prolog-parser/files/5364643/e02.txt)

```
Parse error in line 1
Definition (Atom (f) [])
```

**Comment by e2e4b6b7** [comment]
Хм. А почему бы и нет?...

:- -- ошибка

f. -- корректное объъявление

**Comment by e2e4b6b7** [comment]
Теперь он до точки ест, чтобы снова начать распознавать
